<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="http://www.sourcepit.org/b2/model/0.1" nsPrefix="model">
  <eSubpackages name="common" nsURI="http://www.sourcepit.org/b2/model/0.1/common"
      nsPrefix="common">
    <eClassifiers xsi:type="ecore:EClass" name="Annotatable" abstract="true" interface="true">
      <eOperations name="getAnnotation" eType="#//common/Annotation">
        <eParameters name="source" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="getAnnotationEntry" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eParameters name="source" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="putAnnotationEntry" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eParameters name="source" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="annotations" upperBound="-1"
          eType="#//common/Annotation" containment="true" eOpposite="#//common/Annotation/parent"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Annotation">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
          eType="#//common/Annotatable" eOpposite="#//common/Annotatable/annotations"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="entries" upperBound="-1"
          eType="#//common/EStringMapEntry" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="EJavaFile" instanceClassName="java.io.File"/>
    <eClassifiers xsi:type="ecore:EDataType" name="ELocale" instanceClassName="java.util.Locale"/>
    <eClassifiers xsi:type="ecore:EClass" name="EStringMapEntry" instanceClassName="java.util.Map$Entry">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="module" nsURI="http://www.sourcepit.org/b2/model/0.1/module"
      nsPrefix="module">
    <eClassifiers xsi:type="ecore:EClass" name="AbstractModule" abstract="true" eSuperTypes="#//module/FileContainer #//common/Annotatable #//module/Identifiable">
      <eOperations name="getFacets" lowerBound="1" upperBound="-1">
        <eGenericType eTypeParameter="#//module/AbstractModule/getFacets/T"/>
        <eTypeParameters name="T">
          <eBounds eClassifier="#//module/AbstractFacet"/>
        </eTypeParameters>
        <eParameters name="facetType" lowerBound="1">
          <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
            <eTypeArguments eTypeParameter="#//module/AbstractModule/getFacets/T"/>
          </eGenericType>
        </eParameters>
      </eOperations>
      <eOperations name="hasFacets" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eParameters name="facetType">
          <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
            <eTypeArguments>
              <eUpperBound eClassifier="#//module/AbstractFacet"/>
            </eTypeArguments>
          </eGenericType>
        </eParameters>
      </eOperations>
      <eOperations name="getFacetByName">
        <eGenericType eTypeParameter="#//module/AbstractModule/getFacetByName/F"/>
        <eTypeParameters name="F">
          <eBounds eClassifier="#//module/AbstractFacet"/>
        </eTypeParameters>
        <eParameters name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="resolveReference">
        <eGenericType eTypeParameter="#//module/AbstractModule/resolveReference/P"/>
        <eTypeParameters name="P">
          <eBounds eClassifier="#//module/Project"/>
        </eTypeParameters>
        <eTypeParameters name="F">
          <eBounds eClassifier="#//module/ProjectFacet">
            <eTypeArguments eTypeParameter="#//module/AbstractModule/resolveReference/P"/>
          </eBounds>
        </eTypeParameters>
        <eParameters name="reference" lowerBound="1" eType="#//module/AbstractReference"/>
        <eParameters name="facetType" lowerBound="1">
          <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaClass">
            <eTypeArguments eTypeParameter="#//module/AbstractModule/resolveReference/F"/>
          </eGenericType>
        </eParameters>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="layoutId" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="locales" upperBound="-1"
          eType="#//common/ELocale"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="facets" upperBound="-1"
          eType="#//module/AbstractFacet" containment="true" eOpposite="#//module/AbstractFacet/parent"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BasicModule" eSuperTypes="#//module/AbstractModule"/>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractFacet" abstract="true" eSuperTypes="#//module/Derivable #//common/Annotatable">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
          eType="#//module/AbstractModule" eOpposite="#//module/AbstractModule/facets"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CompositeModule" eSuperTypes="#//module/AbstractModule">
      <eStructuralFeatures xsi:type="ecore:EReference" name="modules" upperBound="-1"
          eType="#//module/AbstractModule"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PluginsFacet">
      <eStructuralFeatures xsi:type="ecore:EReference" name="projects" upperBound="-1"
          eType="#//module/PluginProject" containment="true" eOpposite="#//module/PluginProject/parent"/>
      <eGenericSuperTypes eClassifier="#//module/ProjectFacet">
        <eTypeArguments eClassifier="#//module/PluginProject"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FeaturesFacet">
      <eStructuralFeatures xsi:type="ecore:EReference" name="projects" upperBound="-1"
          eType="#//module/FeatureProject" containment="true" eOpposite="#//module/FeatureProject/parent"/>
      <eGenericSuperTypes eClassifier="#//module/ProjectFacet">
        <eTypeArguments eClassifier="#//module/FeatureProject"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SitesFacet">
      <eStructuralFeatures xsi:type="ecore:EReference" name="projects" upperBound="-1"
          eType="#//module/SiteProject" containment="true" eOpposite="#//module/SiteProject/parent"/>
      <eGenericSuperTypes eClassifier="#//module/ProjectFacet">
        <eTypeArguments eClassifier="#//module/SiteProject"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PluginProject" eSuperTypes="#//module/Project">
      <eOperations name="isFragment" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//module/PluginsFacet"
          eOpposite="#//module/PluginsFacet/projects"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="bundleVersion" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="testPlugin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fragmentHostSymbolicName"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fragmentHostVersion"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FeatureProject" eSuperTypes="#//module/Project #//module/Classified">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//module/FeaturesFacet"
          eOpposite="#//module/FeaturesFacet/projects"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="includedPlugins" upperBound="-1"
          eType="#//module/PluginInclude" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="includedFeatures" upperBound="-1"
          eType="#//module/FeatureInclude" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="requiredFeatures" upperBound="-1"
          eType="#//module/RuledReference" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="requiredPlugins" upperBound="-1"
          eType="#//module/RuledReference" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SiteProject" eSuperTypes="#//module/Project #//module/Classified">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//module/SitesFacet"
          eOpposite="#//module/SitesFacet/projects"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="categories" upperBound="-1"
          eType="#//module/Category" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Project" abstract="true" eSuperTypes="#//module/FileContainer #//module/Derivable #//common/Annotatable #//module/Identifiable">
      <eOperations name="getParent">
        <eGenericType eClassifier="#//module/ProjectFacet">
          <eTypeArguments>
            <eUpperBound eClassifier="#//module/Project"/>
          </eTypeArguments>
        </eGenericType>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ProjectFacet" abstract="true" eSuperTypes="#//module/AbstractFacet">
      <eTypeParameters name="P">
        <eBounds eClassifier="#//module/Project"/>
      </eTypeParameters>
      <eOperations name="getProjects" lowerBound="1">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EEList">
          <eTypeArguments eTypeParameter="#//module/ProjectFacet/P"/>
        </eGenericType>
      </eOperations>
      <eOperations name="getProjectById">
        <eGenericType eTypeParameter="#//module/ProjectFacet/P"/>
        <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eOperations name="resolveReference">
        <eGenericType eTypeParameter="#//module/ProjectFacet/P"/>
        <eParameters name="reference" lowerBound="1" eType="#//module/AbstractReference"/>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FileContainer" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="directory" eType="#//common/EJavaFile"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Derivable" abstract="true" interface="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="derived" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PluginInclude" eSuperTypes="#//module/AbstractStrictReference">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="unpack" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Category">
      <eStructuralFeatures xsi:type="ecore:EReference" name="featureReferences" upperBound="-1"
          eType="#//module/StrictReference" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Classified" abstract="true" interface="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="classifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Identifiable" abstract="true" interface="true">
      <eOperations name="isIdentifyableBy" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eParameters name="identifier" eType="#//module/Identifier"/>
      </eOperations>
      <eOperations name="toIdentifier" lowerBound="1" eType="#//module/Identifier"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ProductsFacet" eSuperTypes="#//module/AbstractFacet">
      <eStructuralFeatures xsi:type="ecore:EReference" name="productDefinitions" upperBound="-1"
          eType="#//module/ProductDefinition" containment="true" eOpposite="#//module/ProductDefinition/parent"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ProductDefinition" eSuperTypes="#//common/Annotatable #//module/Derivable">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
          eType="#//module/ProductsFacet" eOpposite="#//module/ProductsFacet/productDefinitions"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="file" lowerBound="1"
          eType="#//common/EJavaFile"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="productPlugin" lowerBound="1"
          eType="#//module/StrictReference" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="Identifier" instanceClassName="org.sourcepit.b2.model.module.util.Identifier"/>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractReference" abstract="true"
        eSuperTypes="#//common/Annotatable">
      <eOperations name="isSatisfiableBy" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eParameters name="identifier" eType="#//module/Identifiable"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="VersionMatchRule">
      <eLiterals name="compatible"/>
      <eLiterals name="perfect" value="1"/>
      <eLiterals name="equivalent" value="2"/>
      <eLiterals name="greaterOrEqual" value="3"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RuledReference" eSuperTypes="#//module/AbstractReference">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="versionMatchRule" eType="#//module/VersionMatchRule"
          defaultValueLiteral="compatible"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractStrictReference" abstract="true"
        eSuperTypes="#//module/AbstractReference"/>
    <eClassifiers xsi:type="ecore:EClass" name="StrictReference" eSuperTypes="#//module/AbstractStrictReference"/>
    <eClassifiers xsi:type="ecore:EClass" name="FeatureInclude" eSuperTypes="#//module/AbstractStrictReference">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="optional" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="session" nsURI="http://www.sourcepit.org/b2/model/0.1/session"
      nsPrefix="session">
    <eClassifiers xsi:type="ecore:EClass" name="B2Session" eSuperTypes="#//common/Annotatable">
      <eOperations name="getProject" eType="#//session/ModuleProject">
        <eParameters name="groupId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="artifactId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eParameters name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="projects" upperBound="-1"
          eType="#//session/ModuleProject" containment="true" eOpposite="#//session/ModuleProject/session"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="currentProject" lowerBound="1"
          eType="#//session/ModuleProject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ModuleProject" eSuperTypes="#//common/Annotatable">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="groupId" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="session" lowerBound="1"
          eType="#//session/B2Session" eOpposite="#//session/B2Session/projects"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="artifactId" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="directory" lowerBound="1"
          eType="#//common/EJavaFile"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dependencies" upperBound="-1"
          eType="#//session/ModuleDependency" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="moduleModel" eType="#//module/AbstractModule"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="attachments" upperBound="-1"
          eType="#//session/ModuleAttachment" containment="true" eOpposite="#//session/ModuleAttachment/parent"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="environements" upperBound="-1"
          eType="#//session/Environment" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ModuleDependency">
      <eOperations name="isSatisfiableBy" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eParameters name="moduleProject" eType="#//session/ModuleProject"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="groupId" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="artifactId" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="versionRange" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="classifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ModuleAttachment">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="classifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="file" lowerBound="1"
          eType="#//common/EJavaFile"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
          eType="#//session/ModuleProject" eOpposite="#//session/ModuleProject/attachments"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Environment">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="os" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ws" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="arch" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
